#!/usr/bin/env python3

from stripbot.comics import DirkJan, Sigmund, Jeroom
from stripbot.update import get_new_comics
from stripbot.reddit import post_comic
from stripbot.statefile import StateFile

for comic_site in [DirkJan, Sigmund, Jeroom]:
    statefilename = 'state-%s.json' % comic_site.name.lower().replace(' ', '-')
    with StateFile(statefilename) as state:
        posted_ids = set(state.setdefault('posted_ids', []))
        comics = get_new_comics(comic_site, posted_ids)
        state['posted_ids'] = sorted(posted_ids)

        for comic in comics:
            print("posting %s" % (comic))
            post_comic(comic)
            posted_ids.add(comic.id)
            state['posted_ids'] = sorted(posted_ids)
